[project]
name = "cts1_gs_tool_lib"
version = "0.1.0"
description = "Interfaces with forwarder for common ground support functions."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "ruff >= 0.8.1",
    "pytest >= 8.3.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cts1_gs_tool_lib"]
